package com.online.book.store.model;

import com.online.book.store.model.base.BaseGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goods extends BaseGoods<Goods> {
	public static final Goods dao = new Goods();
	
	/*@Override
	public Page<Goods> paginate(int pageNumber, int pageSize, String sql) {
		// TODO Auto-generated method stub
		return super.paginate(pageNumber, pageSize, "select * from goods");
	}*/
}
