package com.online.book.store.model;

import com.online.book.store.model.base.BaseOrders;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Orders extends BaseOrders<Orders> {
	public static final Orders dao = new Orders();
}
