package com.online.book.store.model;

import com.online.book.store.model.base.BaseUserinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Userinfo extends BaseUserinfo<Userinfo> {
	public static final Userinfo dao = new Userinfo();
}
