package com.online.book.store.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.online.book.store.model.Goods;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public void setSid(java.lang.Integer sid) {
		set("sid", sid);
	}

	public java.lang.Integer getSid() {
		return get("sid");
	}

	public void setSname(java.lang.String sname) {
		set("sname", sname);
	}

	public java.lang.String getSname() {
		return get("sname");
	}

	public void setSprice(java.lang.String sprice) {
		set("sprice", sprice);
	}

	public java.lang.String getSprice() {
		return get("sprice");
	}

	public void setNum(java.lang.Integer num) {
		set("num", num);
	}

	public java.lang.Integer getNum() {
		return get("num");
	}

	@Override
	public boolean equals(Object o) {
		// TODO Auto-generated method stub
		Goods g = null;
		if(o instanceof Goods)
			g=(Goods)o;
		return this.getSid()==g.getSid();
	}

	@Override
	public int hashCode() {
		// TODO Auto-generated method stub
		return this.getSid();
	}

}
