package com.online.book.store.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrders<M extends BaseOrders<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCustomer(java.lang.String Customer) {
		set("Customer", Customer);
	}

	public java.lang.String getCustomer() {
		return get("Customer");
	}

	public void setOrderDate(java.util.Date OrderDate) {
		set("OrderDate", OrderDate);
	}

	public java.util.Date getOrderDate() {
		return get("OrderDate");
	}

	public void setShipDate(java.util.Date ShipDate) {
		set("ShipDate", ShipDate);
	}

	public java.util.Date getShipDate() {
		return get("ShipDate");
	}

	public void setShipAddr(java.lang.String ShipAddr) {
		set("ShipAddr", ShipAddr);
	}

	public java.lang.String getShipAddr() {
		return get("ShipAddr");
	}

	public void setShipState(java.lang.String ShipState) {
		set("ShipState", ShipState);
	}

	public java.lang.String getShipState() {
		return get("ShipState");
	}

	public void setShipCost(java.lang.Integer ShipCost) {
		set("ShipCost", ShipCost);
	}

	public java.lang.Integer getShipCost() {
		return get("ShipCost");
	}

	public void setTelephe(java.lang.String telephe) {
		set("telephe", telephe);
	}

	public java.lang.String getTelephe() {
		return get("telephe");
	}

}
