package com.online.book.store.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserinfo<M extends BaseUserinfo<M>> extends Model<M> implements IBean {

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setNumber(java.lang.String number) {
		set("number", number);
	}

	public java.lang.String getNumber() {
		return get("number");
	}

	public void setRelname(java.lang.String relname) {
		set("relname", relname);
	}

	public java.lang.String getRelname() {
		return get("relname");
	}

	public void setTelephe(java.lang.String telephe) {
		set("telephe", telephe);
	}

	public java.lang.String getTelephe() {
		return get("telephe");
	}

	public void setAddr(java.lang.String addr) {
		set("addr", addr);
	}

	public java.lang.String getAddr() {
		return get("addr");
	}

	public void setMail(java.lang.String mail) {
		set("mail", mail);
	}

	public java.lang.String getMail() {
		return get("mail");
	}

}
